language: ruby
install:
  - bundle install --path=mybundle
rvm:
  - 1.9.3
  - 2.1.7
  - 2.2.4
  - 2.3.0
env:
  - CI_ENV=default
script:
  - bundle exec ruby test/unit_test.rb
  - bundle exec ruby test/performance_test.rb 4.5
