language: ruby
install:
  - bundle install --path=mybundle
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
env:
  - CI_ENV=default
script:
  - bundle exec ruby test/unit_test.rb
  - bundle exec ruby test/performance_test.rb 4.5
